version: 3.8

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/surc/vibro/
    ports:
      - "8000:8000"
    # environment:
    #   - DEBUG=1
    #   - DJANGO_ALLOWED_HOSTS=LOCALHOST 127.0.0.1
    # depends_on:
    #   - pgdb
    #   - redis
